language: ruby
rvm:
  - 1.9
  - 2.1
  - 2.2
script:
  - bundle exec rspec spec
  - bundle exec ./prime_numbers.rb
  - bundle exec ./scripts/benchmark.rb -i 1
addons:
  code_climate:
    repo_token: 314f5d120f22aa696128908a4bb57ec3e1252c90521ef7ce15f9b2c737c7d54f